version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: easytoguess
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: eveneasier
    ports:
      - "3306:3306"

  wordpress:
    depends_on:
      - db
    image: wordpress:5.4
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./wp/wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: eveneasier
      WORDPRESS_DB_NAME: wordpress
      WP_DEBUG: 1

  nginx-proxy:
    restart: always
    image: nginx:alpine
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - wordpress
    ports:
      # - 443:443
      - 80:80
